// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitions.sql

package database

import (
	"context"
)

const getCompByStageID = `-- name: GetCompByStageID :one
SELECT c.id, c.created_at, c.updated_at, c.name, c._sport_id FROM competitions c
JOIN editions e ON c.id = e._competition_id
JOIN stages s ON e.id = s._edition_id
WHERE s.id = $1
`

func (q *Queries) GetCompByStageID(ctx context.Context, id int32) (Competition, error) {
	row := q.db.QueryRowContext(ctx, getCompByStageID, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.SportID,
	)
	return i, err
}

const getCompEditionsForSport = `-- name: GetCompEditionsForSport :many
SELECT 
  c.name,
  e.id,
  e.season

FROM competitions c
JOIN editions e ON c.id = e._competition_id
LEFT JOIN sports s ON s.id = c._sport_id

WHERE s.name = $1

ORDER BY c.name
`

type GetCompEditionsForSportRow struct {
	Name   string
	ID     int32
	Season string
}

func (q *Queries) GetCompEditionsForSport(ctx context.Context, name string) ([]GetCompEditionsForSportRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompEditionsForSport, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompEditionsForSportRow
	for rows.Next() {
		var i GetCompEditionsForSportRow
		if err := rows.Scan(&i.Name, &i.ID, &i.Season); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStageByID = `-- name: GetStageByID :one
SELECT id, created_at, updated_at, name, _edition_id FROM stages
WHERE id = $1
`

func (q *Queries) GetStageByID(ctx context.Context, id int32) (Stage, error) {
	row := q.db.QueryRowContext(ctx, getStageByID, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.EditionID,
	)
	return i, err
}

const getStagesForCompEdition = `-- name: GetStagesForCompEdition :many
SELECT 
  id,
  name
FROM stages
WHERE _edition_id = $1
ORDER BY name
`

type GetStagesForCompEditionRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetStagesForCompEdition(ctx context.Context, EditionID int32) ([]GetStagesForCompEditionRow, error) {
	rows, err := q.db.QueryContext(ctx, getStagesForCompEdition, EditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStagesForCompEditionRow
	for rows.Next() {
		var i GetStagesForCompEditionRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
