// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitors.sql

package database

import (
	"context"
)

const getCompetitorByName = `-- name: GetCompetitorByName :one
SELECT id, created_at, updated_at, name, _country, _sport_id FROM competitors
WHERE name = $1
`

func (q *Queries) GetCompetitorByName(ctx context.Context, name string) (Competitor, error) {
	row := q.db.QueryRowContext(ctx, getCompetitorByName, name)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Country,
		&i.SportID,
	)
	return i, err
}

const getCompetitorsForSport = `-- name: GetCompetitorsForSport :many
SELECT 
  c.name

FROM competitors c
LEFT JOIN sports s ON s.id = c._sport_id

WHERE s.name = $1

ORDER BY c.name
`

func (q *Queries) GetCompetitorsForSport(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCompetitorsForSport, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
