// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package database

import (
	"context"
)

const addCountry = `-- name: AddCountry :one
INSERT INTO countries (country_code, name)
VALUES (
  $1,
  $2
)
RETURNING country_code, created_at, updated_at, name
`

type AddCountryParams struct {
	CountryCode string
	Name        string
}

func (q *Queries) AddCountry(ctx context.Context, arg AddCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, addCountry, arg.CountryCode, arg.Name)
	var i Country
	err := row.Scan(
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT country_code, created_at, updated_at, name FROM countries
WHERE country_code = $1
`

func (q *Queries) GetCountryByCode(ctx context.Context, countryCode string) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryByCode, countryCode)
	var i Country
	err := row.Scan(
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
