// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getEvents = `-- name: GetEvents :many
SELECT
  e.id AS event_id,
  e.venue_date,
  e.venue_time,
  e.status,

  c.name AS competition,
  ed.season,
  st.name AS stage,

  hc.name AS home_competitor,
  ac.name AS away_competitor,

  r.home_points,
  r.away_points,
  r.outcome,
  r.forfeit_by

FROM events e
JOIN stages st ON e._stage_id = st.id
JOIN editions ed ON st._edition_id = ed.id
JOIN competitions c ON ed._competition_id = c.id
JOIN sports s ON c._sport_id = s.id
LEFT JOIN competitors hc ON e._home_competitor_id = hc.id
LEFT JOIN competitors ac ON e._away_competitor_id = ac.id
LEFT JOIN results r ON r._event_id = e.id

WHERE ($1::date IS NULL OR e.venue_date = $1::date) AND ($2::text IS NULL OR s.name = $2::text)

ORDER BY
  e.venue_date,
  e.venue_time,
  c.name
`

type GetEventsParams struct {
	DateFilter  sql.NullTime
	SportFilter *string
}

type GetEventsRow struct {
	EventID        int32
	VenueDate      time.Time
	VenueTime      sql.NullTime
	Status         string
	Competition    string
	Season         string
	Stage          string
	HomeCompetitor *string
	AwayCompetitor *string
	HomePoints     sql.NullInt16
	AwayPoints     sql.NullInt16
	Outcome        *string
	ForfeitBy      *string
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEvents, arg.DateFilter, arg.SportFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.VenueDate,
			&i.VenueTime,
			&i.Status,
			&i.Competition,
			&i.Season,
			&i.Stage,
			&i.HomeCompetitor,
			&i.AwayCompetitor,
			&i.HomePoints,
			&i.AwayPoints,
			&i.Outcome,
			&i.ForfeitBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
