// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (status, venue_date, venue_time, _venue_id, _home_competitor_id, _away_competitor_id, _stage_id, details)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id
`

type CreateEventParams struct {
	Status           string
	VenueDate        time.Time
	VenueTime        *time.Time
	VenueID          sql.NullInt32
	HomeCompetitorID sql.NullInt32
	AwayCompetitorID sql.NullInt32
	StageID          int32
	Details          *string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Status,
		arg.VenueDate,
		arg.VenueTime,
		arg.VenueID,
		arg.HomeCompetitorID,
		arg.AwayCompetitorID,
		arg.StageID,
		arg.Details,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getEventByConstraint = `-- name: GetEventByConstraint :exec
SELECT id, created_at, updated_at, status, venue_date, venue_time, _venue_id, _home_competitor_id, _away_competitor_id, _stage_id, details FROM events
WHERE venue_date = $1 AND _stage_id = $2 AND _home_competitor_id = $3 AND _away_competitor_id = $4
`

type GetEventByConstraintParams struct {
	VenueDate        time.Time
	StageID          int32
	HomeCompetitorID sql.NullInt32
	AwayCompetitorID sql.NullInt32
}

func (q *Queries) GetEventByConstraint(ctx context.Context, arg GetEventByConstraintParams) error {
	_, err := q.db.ExecContext(ctx, getEventByConstraint,
		arg.VenueDate,
		arg.StageID,
		arg.HomeCompetitorID,
		arg.AwayCompetitorID,
	)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
  e.venue_date,
  e.venue_time,
  e.status,
  e.details AS event_details,

  v._country,
  v.city,
  v.name AS place_name,

  c.name AS competition,
  ed.season,
  st.name AS stage,

  hc._country AS home_country,
  hc.name AS home_competitor,
  ac._country AS away_country,
  ac.name AS away_competitor,

  r.home_points,
  r.away_points,
  r.outcome,
  r.forfeit_by,
  r.details AS result_details

FROM events e
JOIN stages st ON e._stage_id = st.id
JOIN editions ed ON st._edition_id = ed.id
JOIN competitions c ON ed._competition_id = c.id
LEFT JOIN venues v ON e._venue_id = v.id
LEFT JOIN competitors hc ON e._home_competitor_id = hc.id
LEFT JOIN competitors ac ON e._away_competitor_id = ac.id
LEFT JOIN results r ON r._event_id = e.id

WHERE e.id = $1
`

type GetEventByIDRow struct {
	VenueDate      time.Time
	VenueTime      *time.Time
	Status         string
	EventDetails   *string
	Country        *string
	City           *string
	PlaceName      *string
	Competition    string
	Season         string
	Stage          string
	HomeCountry    *string
	HomeCompetitor *string
	AwayCountry    *string
	AwayCompetitor *string
	HomePoints     sql.NullInt16
	AwayPoints     sql.NullInt16
	Outcome        *string
	ForfeitBy      *string
	ResultDetails  *string
}

func (q *Queries) GetEventByID(ctx context.Context, id int32) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.VenueDate,
		&i.VenueTime,
		&i.Status,
		&i.EventDetails,
		&i.Country,
		&i.City,
		&i.PlaceName,
		&i.Competition,
		&i.Season,
		&i.Stage,
		&i.HomeCountry,
		&i.HomeCompetitor,
		&i.AwayCountry,
		&i.AwayCompetitor,
		&i.HomePoints,
		&i.AwayPoints,
		&i.Outcome,
		&i.ForfeitBy,
		&i.ResultDetails,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT
  e.id AS event_id,
  e.venue_date,
  e.venue_time,
  e.status,

  c.name AS competition,
  ed.season,
  st.name AS stage,

  hc.name AS home_competitor,
  ac.name AS away_competitor,

  r.home_points,
  r.away_points,
  r.outcome,
  r.forfeit_by

FROM events e
JOIN stages st ON e._stage_id = st.id
JOIN editions ed ON st._edition_id = ed.id
JOIN competitions c ON ed._competition_id = c.id
JOIN sports s ON c._sport_id = s.id
LEFT JOIN competitors hc ON e._home_competitor_id = hc.id
LEFT JOIN competitors ac ON e._away_competitor_id = ac.id
LEFT JOIN results r ON r._event_id = e.id

WHERE ($1::date IS NULL OR e.venue_date = $1::date) AND ($2::text IS NULL OR s.name = $2::text)

ORDER BY
  e.venue_date,
  e.venue_time,
  c.name
`

type GetEventsParams struct {
	DateFilter  sql.NullTime
	SportFilter *string
}

type GetEventsRow struct {
	EventID        int32
	VenueDate      time.Time
	VenueTime      *time.Time
	Status         string
	Competition    string
	Season         string
	Stage          string
	HomeCompetitor *string
	AwayCompetitor *string
	HomePoints     sql.NullInt16
	AwayPoints     sql.NullInt16
	Outcome        *string
	ForfeitBy      *string
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEvents, arg.DateFilter, arg.SportFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.VenueDate,
			&i.VenueTime,
			&i.Status,
			&i.Competition,
			&i.Season,
			&i.Stage,
			&i.HomeCompetitor,
			&i.AwayCompetitor,
			&i.HomePoints,
			&i.AwayPoints,
			&i.Outcome,
			&i.ForfeitBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
