// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Competition struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	SportID   int32
}

type Competitor struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Country   *string
	SportID   int32
}

type Country struct {
	CountryCode string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
}

type Edition struct {
	ID            int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Season        string
	CompetitionID int32
}

type Event struct {
	ID               int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Status           string
	VenueDate        time.Time
	VenueTime        *time.Time
	VenueID          sql.NullInt32
	HomeCompetitorID sql.NullInt32
	AwayCompetitorID sql.NullInt32
	StageID          int32
	Details          *string
}

type Result struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	HomePoints int16
	AwayPoints int16
	Outcome    *string
	ForfeitBy  *string
	EventID    int32
	Details    *string
}

type Sport struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Stage struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	EditionID int32
}

type Venue struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	City      *string
	Country   *string
	SportID   int32
}
