// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sports.sql

package database

import (
	"context"
)

const getSports = `-- name: GetSports :many
SELECT sports.name FROM sports
`

func (q *Queries) GetSports(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
