// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package database

import (
	"context"
)

const addVenue = `-- name: AddVenue :one
INSERT INTO venues (name, _country, city, _sport_id)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id
`

type AddVenueParams struct {
	Name    string
	Country *string
	City    *string
	SportID int32
}

func (q *Queries) AddVenue(ctx context.Context, arg AddVenueParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addVenue,
		arg.Name,
		arg.Country,
		arg.City,
		arg.SportID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, created_at, updated_at, name, city, _country, _sport_id FROM venues
WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id int32) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.City,
		&i.Country,
		&i.SportID,
	)
	return i, err
}

const getVenuesForSport = `-- name: GetVenuesForSport :many
SELECT 
  v.id,
  v.name

FROM venues v
LEFT JOIN sports s ON s.id = v._sport_id

WHERE s.name = $1

ORDER BY v.name
`

type GetVenuesForSportRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetVenuesForSport(ctx context.Context, name string) ([]GetVenuesForSportRow, error) {
	rows, err := q.db.QueryContext(ctx, getVenuesForSport, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVenuesForSportRow
	for rows.Next() {
		var i GetVenuesForSportRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
